const { firefox } = require('playwright')
;(async () => {
  const b = await firefox.launch({ headless: true })
  const p = await b.newPage()
  p.on('console', m => console.log('CONSOLE['+m.type()+']:', m.text()))
  p.on('pageerror', e => console.log('PAGEERR:', e.message))
  p.on('requestfailed', r => console.log('REQFAIL:', r.url(), r.failure()?.errorText))
  await p.goto('http://127.0.0.1:5215/', { waitUntil: 'commit', timeout: 20000 })
  await p.waitForTimeout(8000)
  const info = await p.evaluate(()=>({rs:document.readyState, root: document.getElementById('root')?.childElementCount, scripts: document.scripts.length}))
  console.log('INFO:', JSON.stringify(info))
  await b.close()
  console.log('DONE')
})().catch(e => { console.error('ERR:', e.message); process.exit(1) })
