const { firefox } = require('playwright')
const path = require('path')
const BASE='http://127.0.0.1:5191'
const SAMPLE=path.join(__dirname,'sample-mto.xlsx')
;(async()=>{
const b=await firefox.launch({headless:true})
const ctx=await b.newContext({viewport:{width:1440,height:1000}})
const p=await ctx.newPage()
p.on('dialog',d=>d.accept())
await p.addInitScript(()=>{try{localStorage.clear()}catch{}})
await p.goto(`${BASE}/app/project/proj-1`,{waitUntil:'networkidle'})
await p.waitForSelector('text=Maple Grove Estates')
await p.locator('button',{hasText:'MTO'}).first().click();await p.waitForTimeout(400)
await p.getByRole('button',{name:/New MTO/i}).click();await p.waitForTimeout(300)
await p.getByText('Blank take-off').click();await p.waitForTimeout(400)
await p.locator('input[type=file]').first().setInputFiles(SAMPLE);await p.waitForTimeout(900)
await p.getByRole('button',{name:/Save mapping/i}).click();await p.waitForTimeout(600)
const cm=await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('plotline-appdata')||'{}');const proj=d.projects&&d.projects['proj-1'];const cur=(proj.mtoVersions||[]).find(v=>v.isCurrent);return {cm:cur&&cur.columnMap, rows:(cur&&cur.rows||[]).length}})
console.log('columnMap after save:',JSON.stringify(cm.cm),'rows:',cm.rows)
await p.locator('button',{hasText:'Proposal'}).first().click();await p.waitForTimeout(400)
await p.getByRole('button',{name:/Refresh from MTO/i}).click();await p.waitForTimeout(600)
const prop=await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('plotline-appdata')||'{}');const proj=d.projects&&d.projects['proj-1'];return proj.proposal})
console.log('proposal lineItems:',JSON.stringify(prop&&prop.lineItems))
await b.close()
})().catch(e=>{console.error(e);process.exit(2)})
