const { firefox } = require('playwright')
const path = require('path')
const BASE='http://127.0.0.1:5191'
const TPL=path.join(__dirname,'import-tpl.json')
;(async()=>{
const b=await firefox.launch({headless:true})
const p=await b.newContext({viewport:{width:1440,height:1000}}).then(c=>c.newPage())
p.on('dialog',d=>d.accept())
await p.addInitScript(()=>{try{localStorage.clear()}catch{}})
await p.goto(`${BASE}/app/project/proj-1`,{waitUntil:'networkidle'})
await p.waitForSelector('text=Maple Grove Estates')
await p.getByRole('button',{name:/Import$/i}).click();await p.waitForTimeout(300)
let imp=p.locator('input[type=file]')
console.log('file input count', await imp.count())
let target = await imp.count()>1 ? imp.nth(1) : imp.first()
await target.setInputFiles(TPL)
await p.waitForTimeout(700)
console.log('Acme visible count', await p.locator('input[value="Acme Irrigation"]').count())
const snap=await p.evaluate(()=>{const d=JSON.parse(localStorage.getItem('plotline-appdata')||'{}');const pr=d.projects&&d.projects['proj-1'];return {to:pr&&pr.proposal&&pr.proposal.to, lineItems:pr&&pr.proposal&&pr.proposal.lineItems&&pr.proposal.lineItems.map(l=>l.description), company:d.company}})
console.log('snap:',JSON.stringify(snap))
await b.close()
})().catch(e=>{console.error(e);process.exit(2)})
