const { firefox } = require('playwright')
const path = require('path')
const BASE='http://127.0.0.1:5191'
const LOGO=path.join(__dirname,'logo-test.png')
;(async()=>{
const b=await firefox.launch({headless:true})
const p=await b.newContext({viewport:{width:1440,height:1000}}).then(c=>c.newPage())
p.on('dialog',d=>d.accept())
await p.addInitScript(()=>{try{localStorage.clear()}catch{}})
await p.goto(`${BASE}/app/project/proj-1`,{waitUntil:'networkidle'})
await p.waitForSelector('text=Maple Grove Estates')
const logoBtn=p.getByRole('button',{name:/Upload your company logo/i})
const [chooser]=await Promise.all([p.waitForEvent('filechooser'),logoBtn.first().click()])
await chooser.setFiles(LOGO)
await p.waitForTimeout(1500)
const snap=await p.evaluate(()=>JSON.parse(localStorage.getItem('plotline-appdata')||'{}'))
console.log('keys:', Object.keys(snap))
console.log('company:', typeof snap.company, snap.company && JSON.stringify({name:snap.company.name, has:!!snap.company.logoDataUrl, len: snap.company.logoDataUrl&&snap.company.logoDataUrl.length}))
await b.close()
})().catch(e=>{console.error(e);process.exit(2)})
